name: Workflow Unit Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, json, mysqli, pdo_mysql, bcmath, fileinfo
        coverage: none

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Copy .env file
      run: cp .env.production .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Run database migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: production_database
        DB_USERNAME: your_username
        DB_PASSWORD: your_password
      run: php artisan migrate --force

    - name: Run unit tests
      env:
        APP_ENV: production
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: production_database
        DB_USERNAME: your_username
        DB_PASSWORD: your_password
      run: php artisan test --env=production --no-interaction --stop-on-failure
