name: Workflow Unit Tests

on:
  push:
    branches:
      - staging

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: u329657931_staging
          MYSQL_USER: u329657931_pantau
          MYSQL_PASSWORD: LdimW&/8Zl!
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, json, mysqli, pdo_mysql, bcmath, fileinfo
        coverage: none

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Set up .env file
      run: |
        cp .env.example .env
        php artisan key:generate
        php artisan config:cache

    - name: Test DB connection
      run: |
        php -r "
        try {
            \$pdo = new PDO('mysql:host=' . getenv('DB_HOST') . ';port=' . getenv('DB_PORT') . ';dbname=' . getenv('DB_DATABASE'), getenv('DB_USERNAME'), getenv('DB_PASSWORD'));
            echo 'Connected successfully!';
        } catch (PDOException \$e) {
            echo 'Connection failed: ' . \$e->getMessage();
        }"
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: u329657931_staging
        DB_USERNAME: u329657931_pantau
        DB_PASSWORD: LdimW&/8Zl!

    - name: Run database migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: u329657931_staging
        DB_USERNAME: u329657931_pantau
        DB_PASSWORD: LdimW&/8Zl!
      run: php artisan migrate --seed --force

    - name: Run unit tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: u329657931_staging
        DB_USERNAME: u329657931_pantau
        DB_PASSWORD: LdimW&/8Zl!
      run: php artisan test 
