name: Workflow Unit Tests

on:
  push:
    branches:
      - staging

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, json, mysqli, pdo_mysql, bcmath, fileinfo
        coverage: none

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Set up .env file
      run: |
        cp .env.example .env
        php artisan key:generate
        php artisan config:cache

    - name: Run database migrations
      env:
          APP_ENV: production
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: u329657931_testing
          DB_USERNAME: u329657931_test
          DB_PASSWORD: LdimW&/8Zl!
      run: php artisan migrate --seed --force

    - name: Run unit tests
      env:
        APP_ENV: production
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: u329657931_testing
        DB_USERNAME: u329657931_test
        DB_PASSWORD: LdimW&/8Zl!
      run: php artisan test --env=production --no-interaction --stop-on-failure
